spring:
    application:
        name: api-gateway

    cloud:
        gateway:
            routes:
                - id: auth_service_route
                  uri: http://localhost:7786
                  predicates:
                      - Path=/auth/**
                - id: user_service_route
                  uri: lb://USER-SERVICE
                  predicates:
                      - Path=/users/**
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:8080/.well-known/jwks.json

logging:
    level:
        ROOT: INFO
        com.top: DEBUG
        io.confluent.kafka: ERROR
        org.apache.kafka: ERROR

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
